### ISSUE TITLE
npm script doesn't work on windows

### ISSUE THREAD

**Issue by henofdante** [gadhagod/vscode-chrome-extension-devtools#5]
should use node and backslash
```json
 "scripts": {
    "watch": "**node** .**\\**node_modules\\webpack\\bin\\webpack.js --mode=development --watch --config config\\webpack.config.js",
    "build": "**node** .**\\**node_modules\\webpack\\bin\\webpack.js --mode=production --config config\\webpack.config.js"
  }
```

**Comment by gadhagod** [comment]
Thanks for letting me know @henofdante. Please tell me what error you receive when using the extension.

**Comment by tylerslemke** [comment]
@gadhagod  - The issue is that the npm run watch and run build commands fail with the following error:

> ./node_modules/webpack/bin/webpack.js --mode=production --config config/webpack.config.js

'.' is not recognized as an internal or external command,
operable program or batch file.

switching the scripts to use npx seems to work in Windows 10 just fine:

  "scripts": {
    "watch": "npx webpack --mode=development --watch --config config/webpack.config.js",
    "build": "npx webpack --mode=production --config config/webpack.config.js"
  },

**Comment by gadhagod** [comment]
Thanks for the help @henofdante. Greatly appreciated.
Since I'm trying to use webpack from the `node_modules` directory, the `node` command be a better alternative. `npx` uses the globally installed webpack, whereas `node node_modules/webpack/bin/webpack.js` uses the local. 
Working on a fix.

**Comment by gadhagod** [comment]
The chrome extension creation client already uses the `node` command, and you may have an old version of the extension. Please uninstall your extension and re-install the latest version (2.0.1).
